version: '3.5'
services:
  # django app
  elri-node1:
    volumes:
      - elri-storage:/storage:rw
      - elri-certs:/certificates:ro
  # Linux POSTGRES Server 
  postgres-server:
    volumes:
      - elri-db:/var/lib/postgresql/data:rw
  # NGINX webserver
  nginx:
    ports:
      - "80:80"
    volumes:
      - web-certs:/etc/ssl/certs:ro
      - web-keys:/etc/ssl/private:ro
volumes:
  elri-db:
    name: elri-db
  elri-storage:
    name: elri-storage
  elri-certs:
    name: elri-certs
  web-certs:
    name: web-certs
  web-keys:
    name: web-keys
secrets:
  db.secret:
    file: db_secret.properties
  app.secret:
    file: nrs_secret.properties
  web.secret:
    file: web_secret.properties
networks:
  elri-nw:
    name: elri-nw
    ipam:
      config:
        - subnet: 10.1.0.0/24